spring.application.name=eixo
server.port=8082

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console web do H2 para você visualizar as tabelas no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop